### ISSUE TITLE
Support building of static libraries on Alpine Linux

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimagetool#1]
Cross-reference to the Alpine Linux feature report:
* https://gitlab.alpinelinux.org/alpine/aports/-/issues/15052

**Comment by probonopd** [comment]
In the record time of just 2 minutes after opening the feature request, [alice](https://gitlab.alpinelinux.org/psykose) has made a `libassuan-static` package.

And just a few minutes later, [libassuan-static](https://pkgs.alpinelinux.org/contents?branch=edge&name=libassuan%2dstatic&arch=x86_64&repo=main) appeared on pkgs.alpinelinux.org for edge.

Each May and November Alpine Linux makes a release branch from edge, which probably means that in November 2023, the libassuan-static package will be part of the then-released Alpine Linux v3.19.

**Comment by TheAssassin** [comment]
We also need static flavors of libmount and libblkid, apparently. @probonopd could you open issues upstream, please?

**Comment by probonopd** [comment]
What pulls these dependencies in? Asking because I don't remember those from static-tools.

**Comment by probonopd** [comment]
No upstream issue needed, as in edge these are already there, as part of `util-linux-static`:
https://pkgs.alpinelinux.org/contents?file=&path=&name=util-linux-static&branch=edge&repo=main&arch=x86_64

**Comment by TheAssassin** [comment]
Seems like something changed so these are needed for any build that sets `-static`... I'll try that one, thanks!

**Comment by TheAssassin** [comment]
Works, thanks. PR is on the way. The binary size increases by less than 3M when building everything statically. We can optimize that later on if we like.
