### ISSUE TITLE
Automatically download suitable runtime

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimagetool#11]
Since we no longer embed a binary runtime in `appimagetool`'s binary (or otherwise ship runtime files), we should automatically download an official firmware from https://github.com/AppImage/type2-runtime/. This is needed to make this version of appimagetool a drop-in replacement.

**Comment by TheAssassin** [comment]
I'm not sure we can statically link libcurl so easily. It pulls in a _lot_ of dependencies. I'm tempted to just use `dlopen()`...

**Comment by probonopd** [comment]
...or just check for the presence of system-provided `curl` and `wget` on the `$PATH`, and use them. This way, the system takes care of the certificates as well.
