### ISSUE TITLE
Update help text in README

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimagetool#15]
Regression from https://github.com/AppImage/appimagetool/commit/8d362e4ee99972812fdd11799d4187189b8dcf24, which removed the code but forgot to update the documentation.

**Comment by probonopd** [comment]
@TheAssassin not sure what you mean, I don't see the Bintray stuff mentioned anywhere anymore?

**Comment by TheAssassin** [comment]
You are right, I had an old copy of the file.
