### ISSUE TITLE
Add custom TLS certificate chain lookup

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimagetool#24]
We can tell from experience that using prebuilt libcurl binaries can lead to problems when used outside of the distribution they were built for. Most commonly, it cannot find the system CA chain as the paths vary quite drastically across platforms.

In our officially released AppImages, we embed Alpine Linux's static build of libcurl. We should investigate whether we need a custom, cross-platform certificate chain lookup to make our tool work reliably across a defined (minimum, tested) set of platforms.

Note: we could even add some automated smoke testing on a variety of distributions with Docker on GitHub actions.

As an alternative, we could ship a CA chain as a fallback. In the past, we always considered that to be a UX quality degradation and strongly preferred using the system chains, though.

@probonopd please link to the related point in your desktop platform issues list.

**Comment by probonopd** [comment]
https://gitlab.com/probono/platformissues (but GitLab shows a 503 at the moment).

**Comment by probonopd** [comment]
As anticipated, "Failed to download runtime file" on

https://mirrorcache.opensuse.org/distribution/openSUSE-current/live/openSUSE-Leap-15.5-KDE-Live-aarch64-Media.iso

**Comment by probonopd** [comment]
The more robust approach would be to use wget/curl from the system.

**Comment by TheAssassin** [comment]
We try to avoid system dependencies, though.
