### ISSUE TITLE
Proper Github sponsor integration?

### ISSUE THREAD

**Issue by hopelessdecoy** [AppImage/appimagetool#41]
Is there anyway Appimagetool could be sponsor-able on Github? PayPal is great and all but this method would be directly connected and accessible via the repo for monthly donations. KDE does it and it's nice! Plus then the profile here on GitHub can display that I sponsor you and people who look at my repo can be drawn to the project.

**Comment by probonopd** [comment]
Thanks for asking, but the project is currently not looking for sponsorships.

**Comment by hopelessdecoy** [comment]
> Thanks for asking, but the project is currently not looking for sponsorships.

Ok, thanks for you your hard work anyways. I'll continue contributing through PayPal when I can. 
Appimage has been the format I've been shipping my apps in so I want to see the project continue!
