### ISSUE TITLE
Default to a sensible zstd compression level

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimagetool#42]
Default to a sensible zstd compression level to improve application startup times. Data:

https://github.com/AppImage/AppImageKit/issues/478#issuecomment-1944449840

**Comment by TheAssassin** [comment]
Define "sensible".

**Comment by probonopd** [comment]
A reasonably good tradeoff between
* Good compression
* Fast application startup times
* High zsync efficiency

**Comment by Samueru-sama** [comment]
I think this issue can be closed, it ended up being the issue of the default block size, even back then I noticed that there was something other than the compression level at play.

Now librewolf takes: 

* 2.5 seconds with the original gzip that the official appimage comes with (111.1 MiB)
* 1.9 seconds with **zstd level 20** (100.9 MiB)
* 1.7 seconds with zstd level 1 (124 MiB)

The difference between zstd 1 and 20 is 0.2 seconds, in other words it really isn't a big deal that zstd 15 is the default being used.

And native non appimage librewolf takes 0.9 seconds to start, so the overhead of the appimage is less than 1 second for my old broadwell cpu.

**Comment by probonopd** [comment]
Reference:

* https://github.com/AppImage/AppImageSpec/issues/44

**Comment by adrianinsaval** [comment]
> I think this issue can be closed, it ended up being the issue of the default block size, even back then I noticed that there was something other than the compression level at play.

so how are you making your appimages now? Or has the default blocksize been changed in appimagetol?

**Comment by Samueru-sama** [comment]
> > I think this issue can be closed, it ended up being the issue of the default block size, even back then I noticed that there was something other than the compression level at play.
> 
> so how are you making your appimages now? Or has the default blocksize been changed in appimagetol?

It was changed [here](https://github.com/AppImage/appimagetool/commit/81ee1db4946780292cd046d4c269a9b4fd7bc29d).
