### ISSUE TITLE
Docker issue when compiling

### ISSUE THREAD

**Issue by dzwdev** [AppImage/appimagetool#43]
`systemctl start docker
ARCH=x86_64 bash ./ci/build-in-docker.sh   
+ [[ x86_64 == '' ]]
+ case "$ARCH" in
+ image_prefix=amd64
+ platform=linux/amd64
+ image=amd64/alpine:edge
+++ dirname ./ci/build-in-docker.sh
++ readlink -f ./ci/..
+ repo_root=/home/pc/Downloads/FlareGet/Compressed/appimagetool-main
++ id -u
+ uid=1000
+ docker pull amd64/alpine:edge
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=amd64%2Falpine&tag=edge": dial unix /var/run/docker.sock: connect: permission denied
`

how to fix this?
and is there a compiled release to use directly?
i'm using manjaro

**Comment by probonopd** [comment]
Can you use a precompiled one from https://github.com/AppImage/appimagetool/releases/tag/continuous?

**Comment by Randrianasulu** [comment]
may be also check that user actually in "docker" group, or ran with sudo as root ?

**Comment by probonopd** [comment]
It compiles with Docker in GitHub Actions as of today, hence closing.
