### ISSUE TITLE
downloading appimagetool fails

### ISSUE THREAD

**Issue by stsp** [AppImage/appimagetool#60]
My script uses this URL:
https://github.com/AppImage/appimagetool/releases/download/continuous/
But it seems to no longer exist?

**Comment by probonopd** [comment]
Please wait until the next build has succeeded.

Root cause:
* https://github.com/AppImage/type2-runtime/issues/51

**Comment by stsp** [comment]
Ok, works again, thanks.

**Comment by probonopd** [comment]
The URLs have changed again, hence you will need to download the latest `appimagetool` again. I'd like to avoid situations like this by

* https://github.com/AppImage/appimagetool/issues/61

**Comment by TheAssassin** [comment]
> The URLs have changed again, hence you will need to download the latest appimagetool again

You could have solved the core issue rather than pushing a bunch of workarounds titled "quick fix"...

**Comment by probonopd** [comment]
Well, I had assumed that _someone_ had _intentionally_ renamed the runtime binaries...

**Comment by TheAssassin** [comment]
Yeah, me too. That's why I kept that distinguishing suffix. Unfortunately, I didn't think of the effects it would have on appimagetool, which might be because I rarely work with the code these days due to this work being really exhausting (not code wise, discussion overhead).
