### ISSUE TITLE
Regression? higher startup time with zstd compression

### ISSUE THREAD

**Issue by Samueru-sama** [AppImage/appimagetool#64]
I've been testing this appimagetool now that the static runtime is used automatically. I like that I can select the zstd compression level to use, however during testing I've noticed that appimages made with this appimagetool take longer to launch than appimages made with gzip compression.

For these benchmarks I've used the [zen-browser appimage ](https://github.com/zen-browser/desktop/releases/tag/1.0.0-a.13) (the specific build, which targets x86_64 v3). 

Using appimagetool I made two appimages, one using zstd level 22 compression (the highest):

`./appimagetool-x86_64.AppImage --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 22 squashfs-root` which results in an appimage size of 73.7 MiB

And another using level 1:

`./appimagetool-x86_64.AppImage --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 1 squashfs-root` which results in an appimage size of 96.0 MiB

And test it how long it took for each appimage to start, using this hacky script which gets when the application launches by checking the window class in i3wm: https://pastebin.com/qH7DwcQv

The appimages were all on placed on RAM before being launched to prevent the ssd causing any issue, here are the results: 

Screenshot: https://imgur.com/xzMirgX.png

First this is how long it takes for the original appimage to start after 4 passes: 

```
Time taken: 2359 miliseconds
Time taken: 2626 miliseconds
Time taken: 2257 miliseconds
Time taken: 2755 miliseconds
```

This is how long it takes for the zstd-22 appimage to start, which it is expected to be higher since it is using a very high compression level: 

````
Time taken: 3534 miliseconds
Time taken: 3571 miliseconds
Time taken: 3688 miliseconds
Time taken: 3767 miliseconds
````

This is how long it takes with zstd-1, odd that it still takes longer than the original appimage: 

```
Time taken: 2975 miliseconds
Time taken: 3116 miliseconds
Time taken: 2962 miliseconds
Time taken: 3130 miliseconds
```

Why I think that there is a regression, is that if we make the zstd squashfs image directly, and then add it to the runtime (bypass appimagetool all together) then, it only takes ~1.6 seconds to start the appimage as expected. 

```
Time taken: 1603 miliseconds
Time taken: 1619 miliseconds
Time taken: 1596 miliseconds
Time taken: 1632 miliseconds
```

That "manual" appimage was made using `mksquashfs ./squashfs-root Manual-zstd-1 -comp zstd -Xcompression-level 1` and then using the runtime [from here](https://github.com/AppImage/type2-runtime/releases/tag/continuous) I appended it with `cat Manual-zstd-1 >> runtime-x86_64`

I don't think this is an issue with the runtime, I don't know if the issue is that appimagetool is using different block sizes when making the squashfs image, there is a 1.4 MiB size difference between the manual-zstd1 appimage and the zstd1 appimage made with appimagetool.

**Comment by Samueru-sama** [comment]
The issue is that appimagetool sets the [block size to 1MB here](https://github.com/AppImage/appimagetool/blob/main/src/appimagetool.c#L164)

What's the default block size of mksquashfs? 

I tested manually making a manual appimage this time passing the argument `-b 1MB` to `mksquashfs` and now the resulting appimage has the issue that it takes longer to start. 

Here is a test showing the two, the difference in the startup time is quite big:

![image](https://github.com/user-attachments/assets/85a08d4d-33a4-4107-802b-23bc2f1a64b0)

What's interesting is that the `-b 1M` appimage is `1.4 MiB` **bigger** than the same appimage without giving the block size, even though the comment in the code says that it could produce a smaller appimage.

**Comment by Samueru-sama** [comment]
I have also tested some different block sizes, for some reason 4M block fails to be made even though it should be possible? 

512K takes 2.3s on average to start.
64K is the same as default (128K), at most there is a 50ms difference in favor of 64K.

@mgord9518 Sorry for the ping, you are the author of the original switch to 1MB block size, what do you think of my findings?

If anyone wants the appimages I've made to test just let me know and I'll link them, There is also these builds of [appimagetool](https://github.com/Samueru-sama/appimagetool/releases) that use the default 128K blocksize to make comparisons.

**Comment by mgord9518** [comment]
@Samueru-sama Interesting. Yeah it is true that a larger block size can increase start time, but it should almost always improve compression ratio. I don't believe 4MiB is yet possible, SquashFS currently has a hardcoded 1MiB max but they're talking about upping it in the future. The format has the capability for higher block sizes (either 8 or 16MiB), it just isn't in the spec.

Back when I pushed it, I had done some small-scale tests which reflected a negligible startup difference but a 5-10% shrink in size. Unfortunately that was a while ago and I don't even remember what AppImages I tested it on. Have you tested with other compression algorithms? I vaguely remember ZSTD having bad performance in some tests

**Comment by probonopd** [comment]
Yes, we want to standardize on zstandard. Unless someone has hard proof that something else would be better in most cases.

**Comment by Samueru-sama** [comment]
> Yes, we want to standardize on zstandard. Unless someone has hard proof that something else would be better in most cases.

Well with the current block size gzip is a demonstrably better algo, even when using zstd-1 which makes the appimage bigger it still takes longer to start than gzip.

**Comment by probonopd** [comment]
Thanks @TheAssassin for looking into this.

Someone imho still should systematically(!) test all of this (= compression algorithm, compression factor, block size), in terms of

* Size
* Startup time
* zsync efficiency

so that we can choose the best tradeoff.

**Comment by mgord9518** [comment]
It might be worth noting that using libdeflate has significantly faster (2x) results than zlib on zlib-compressed SquashFS files. I currently have it implemented in my squashfuse-zig library, so it might be a good option to backport to the original squashfuse project if zstd shows to have bad performance.

**Comment by probonopd** [comment]
Interesting! One additional candidate to benchmark.

**Comment by Samueru-sama** [comment]
I think you also need to consider using dwarfs instead of squashfs. But for that there is an issue opened already.

I will add that when zstd is used, and the compression level is set very low instead of the default level 15, the speed it takes for applications to open is very similar to the speed it would take a native application, like about 0.6 second difference a most for web browsers compared to the native package, and it is likely less on newer hardware, I have a broadwell CPU which is old.

**Comment by probonopd** [comment]
Indeed. dwarfs, too.

Someone really needs to systematically test all this stuff.

Preferably in a reproducible setup using GitHub Actions.

**Comment by mgord9518** [comment]
I've messed with DwarFS it has some serious issues for use in AppImage

1: It's licensed GPL3, so the AppImage itself would have to be distributed under a compatible license 
2: The binaries are quite large (I think 8MB uncompressed, ~3 when compressed with Zopfli), so they're only beneficial for quite large applications. 

Don't get me wrong it's an incredible format and the compression ratios blow SquashFS out of the water, but it would only be able to benefit some niche scenarios like FreeCAD or SuperTuxKart: GPL3 applications that are massive enough to benefit from the high compression

**Comment by probonopd** [comment]
Indeed, GPL3 is not what we are looking for, and the size overhead also seems very high. I am intrigued about using zopfli to reduce the size of the AppImage runtime though...

**Comment by mgord9518** [comment]
It's something I'm doing in my shappimage project, but for native executables something like UPX might make more sense

**Comment by ThisIsFineTM** [comment]
@Samueru-sama Semi-relevant side note: zstd level 22 is in `--ultra` territory, which uses a strategy that requires more memory than other strategies used in zstd and is slowest to decompress. Dropping a link to the settings by compression level if you want to see which levels use which strategy. 

https://github.com/facebook/zstd/blob/def3ee9548bdfac07baf4adf38178ca6eac5e265/lib/compress/clevels.h#L25

**Comment by Samueru-sama** [comment]
> @Samueru-sama Semi-relevant side note: zstd level 22 is in `--ultra` territory, which uses a strategy that requires more memory than other strategies used in zstd and is slowest to decompress. Dropping a link to the settings by compression level if you want to see which levels use which strategy.
> 
> https://github.com/facebook/zstd/blob/def3ee9548bdfac07baf4adf38178ca6eac5e265/lib/compress/clevels.h#L25

I haven't seen much difference in the startup time between zstd15 and zstd22 on the benchmarks I do. 

I just recently tested with a puddletag appimage: 

zstd15 and zstd22 use 128K blocks while zstd15-1M is using 1MB blocks. 

![image](https://github.com/user-attachments/assets/94351743-4783-4239-9c6a-ccc77b0b40c7)

So the launch times are:  

~1.25 seconds for zstd15

~1.25 seconds for zstd22 (no difference, maybe 10ms slower on average)

**~1.9** seconds for the zstd15 1MB block appimage and 1MB also results in a bigger appimage.
