### ISSUE TITLE
Possible issue with Icons and Appimage's new runtime

### ISSUE THREAD

**Issue by philmb3487** [AppImage/appimagetool#68]
There seems to be an issue with icon generation on a newer runtime of appimagetool.

Could someone with more experience have a look at the bug report I filed here?
https://github.com/ivan-hc/Steam-appimage/issues/27

Where is the snafu with image generation in this case?

```
thumbnail managers should adapt to the work of AppImage packagers, not the other way around
```
Is this the policy of the project?

Thanks!

**Comment by philmb3487** [comment]
Yes, I can summarize. The gist of it is that some people are generating AppImages with `zstd` compression, and that is not supported out of the box by libappimage.

Would it be possible to add this support?

Arch Linux seems to enable fuse to get that support, squashfuse then needs to be compiled with `zstd` support turned on. That's a lot of switches that might or might not be enabled, depending on the distribution, and I think thumbnails should always be available in any case.

See my findings here,
https://github.com/ivan-hc/Steam-appimage/issues/27#issuecomment-2365229961

So, I propose either,

1) better zstd support out of the box,
2) document what needs to be done if Thumbnails cannot be shown on *some* appimages (out of the box it would be fine with xz, zip images,


```
Squashfs image uses (null) compression, this version supports only xz, zlib.
ERROR: appimage_read_file_into_buffer_following_symlinks : sqfs_open_image error: /home/phil/Applications/Steam-1.0.0.81-2-3-x86_64.appimage
```

**Comment by probonopd** [comment]
Hi @philmb3487, thanks for summarizing. That sees to be a feature request for libappimage

* https://github.com/AppImageCommunity/libappimage/issues/193
