### ISSUE TITLE
Latest release broke running in gitlab CI

### ISSUE THREAD

**Issue by Ayush1325** [AppImage/appimagetool#79]
Not really sure what happened but the latest `appimagetool` seems to no longer work in Gitlab CI (with docker runner). 
The project in question is [bb-imager-rs](https://openbeagle.org/ayush1325/bb-imager-rs).

Here is the error I am getting in CI:
```
sqfs_read_range error: File exists
Failed to extract AppImage
```

Full CI logs can be found here: https://openbeagle.org/ayush1325/bb-imager-rs/-/jobs/45335

The make rule I am using to generate appimages is as follows:
```make
package-gui-linux-appimage-%: build-gui-%
	$(info "Create GUI Linux Appimage $*")
	mkdir -p ${RELEASE_DIR_LINUX}/$*/AppDir/usr/bin
	cp ${GUI_ASSETS_LINUX}/appimage/AppRun ${RELEASE_DIR_LINUX}/$*/AppDir/AppRun
	cp target/$*/release/bb-imager-gui ${RELEASE_DIR_LINUX}/$*/AppDir/usr/bin/
	cp ${GUI_ASSETS_LINUX}/BeagleBoardImager.desktop ${RELEASE_DIR_LINUX}/$*/AppDir/
	sed -i "s/^X-AppImage-Version=0.0.0/X-AppImage-Version=${VERSION}/" ${RELEASE_DIR_LINUX}/$*/AppDir/BeagleBoardImager.desktop
	cp gui/assets/icons/icon.png ${RELEASE_DIR_LINUX}/$*/AppDir/bb-imager.png
	ARCH=${APPIMAGE_ARCH_$*} $(APPIMAGETOOL) --appimage-extract-and-run ${RELEASE_DIR_LINUX}/$*/AppDir ${RELEASE_DIR_LINUX}/$*/BeagleBoardImager.AppImage
	rm -rf ${RELEASE_DIR_LINUX}/$*/AppDir
```

**Comment by probonopd** [comment]
Thanks for reporting. Do you know when was the last "known good" BeagleBoardImager build run?

**Comment by Ayush1325** [comment]
> Thanks for reporting. Do you know when was the last "known good" BeagleBoardImager build run?

Around 3 days ago. Just prior to the new appimagetool release.

**Comment by Ayush1325** [comment]
Seems, it was some problem with the runner.
